name: flutter_starter
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  injectable: ^2.4.4
  http: ^0.13.4
  build_runner: ^2.4.6
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.0.13
  http_interceptor: ^1.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.9.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

  fonts:

    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-ExtraBold.ttf
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-ExtraLight.ttf
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Light.ttf
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/plus_jakarta_sans/PlusJakartaSans-SemiBold.ttf
